// <auto-generated />
using System;
using EntityFrameWorkCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameWorkCore.Data.Migrations
{
    [DbContext(typeof(FootballLeagueDbContext))]
    [Migration("20251021151450_SeededTeams")]
    partial class SeededTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameWorkCore.Domain.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("EntityFrameWorkCore.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Italy",
                            CreatedDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "AC Milan"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Italy",
                            CreatedDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Inter Milan"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Italy",
                            CreatedDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = 4,
                            Country = "England",
                            CreatedDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = 5,
                            Country = "England",
                            CreatedDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 6,
                            Country = "England",
                            CreatedDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Chelsea"
                        },
                        new
                        {
                            Id = 7,
                            Country = "England",
                            CreatedDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Liverpool"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
